"""
Django settings for amx_crm_dev project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f0unobs6ks9^e@trp6(4!wadm99y&1&4tu&t9sy7o=l6-%w=f0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CSRF_USE_SESSIONS = True

ALLOWED_HOSTS = ['*','142.93.214.65', 'amx-crm-dev.thestorywallcafe.com', 'www.amx-crm-dev.thestorywallcafe.com','https://einv-apisandbox.nic.in']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Crm_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'amx_crm_dev'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amx_crm_dev.urls'

CROS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS =[
    'DELETE','PUT','POST','GET'
]

CROS_ALLOW_METHODS =[
    'Content-Type',
]

ROOT_URLCONF = 'amx_crm_dev.urls'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'amxdrone123@gmail.com'
EMAIL_HOST_PASSWORD = 'kclpzrfgcmsrbase'
EMAIL_PORT = 587

SIMPLE_JWT = {
 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
 'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
 'AUTH_HEADER_TYPES': ('Bearer',),

}

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = ['Authorization']


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amx_crm_dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    #}
#
#}

DATABASES = {
      'default': { 
	 'ENGINE': 'django.db.backends.mysql',
	  'OPTIONS': {
	       'read_default_file': '/amx-crm-dev/auth/mysql.cnf',
		},
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = '/amx-crm-dev/site/public/static'
MEDIA_ROOT = '/amx-crm-dev/site/public/media'

STATICFILES_DIRS = [
    '/amx-crm-dev/site/public/static/frontend'
]


RAZORPAY_KEY_ID = 'rzp_test_Z6PoT6HRL71TiC'
RAZORPAY_KEY_SECRET = 'HXoWkrEAODf02TD7IPpMJOES'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

CORS_ALLOWED_ORIGINS = [
"https://amx-crm-dev.thestorywallcafe.com",
"http://localhost:4200",
"http://127.0.0.1:8000",
]
