# Generated by Django 4.2.8 on 2024-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequestcompanydetails',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
