# Generated by Django 4.2.8 on 2024-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0006_customuser_gstin_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvoice',
            name='ewaybill_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
