# Generated by Django 4.2.8 on 2024-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominvoice',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
