# Generated by Django 4.2.8 on 2024-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0002_alter_custominvoice_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
