# Generated by Django 4.2.8 on 2024-01-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0004_invoicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='invoice_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='invoice_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.invoicestatus'),
        ),
    ]
