# Generated by Django 4.2.8 on 2024-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0005_additem_invoice_payload_additem_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='invoice_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
