# Generated by Django 4.2.8 on 2024-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0007_customuser_billing_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='billing_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='billing_state_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='billing_state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='billing_state_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='shipping_state_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='shipping_state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='shipping_state_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
