# Generated by Django 4.2.8 on 2024-02-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0008_changerequestcompanydetails_billing_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='ewaybill_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
