# Generated by Django 4.2.8 on 2024-02-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0009_additem_ewaybill_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einvoice',
            name='data',
        ),
    ]
