# Generated by Django 4.2.8 on 2024-02-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0010_remove_einvoice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
