# Generated by Django 4.2.8 on 2024-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0011_changerequestcompanydetails_user_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
