# Generated by Django 4.2.8 on 2024-02-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0012_einvoice_api_response_einvoice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.additem'),
        ),
    ]
