# Generated by Django 4.2.8 on 2024-02-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0013_einvoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einvoice',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='acknowledgment_number',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='ewbdt',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='ewbno',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='ewbvalidtill',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='irn',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='signedinvoice',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='signedqrcode',
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='status',
        ),
    ]
