# Generated by Django 4.2.8 on 2024-02-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0014_remove_einvoice_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoice',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.additem'),
        ),
    ]
