# Generated by Django 4.2.8 on 2024-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0015_alter_einvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='e_waybill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
