# Generated by Django 4.2.8 on 2024-02-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0016_einvoice_e_waybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstRateValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstrates', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
