# Generated by Django 4.2.8 on 2024-02-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0017_gstratevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='cgst_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='hsn_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='igst_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='sgst_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
