# Generated by Django 4.2.8 on 2024-02-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0018_drone_cgst_amount_drone_hsn_number_drone_igst_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='cgst_amount',
            new_name='cgstvalue',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='igst_amount',
            new_name='igstvalue',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='sgst_amount',
            new_name='sgstvalue',
        ),
    ]
