# Generated by Django 4.2.8 on 2024-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0019_rename_cgst_amount_drone_cgstvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominvoice',
            name='hsn_number',
        ),
        migrations.RemoveField(
            model_name='custominvoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='custominvoice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='custom_item_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
