# Generated by Django 4.2.8 on 2024-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0020_remove_custominvoice_hsn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='amount_to_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='sum_of_cgst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='sum_of_discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='sum_of_igst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='sum_of_item_total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='sum_of_sgst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
