# Generated by Django 4.2.8 on 2024-02-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0021_additem_amount_to_pay_additem_sum_of_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='sum_of_price_after_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
