# Generated by Django 4.2.8 on 2024-02-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0022_additem_sum_of_price_after_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominvoice',
            old_name='item_name',
            new_name='invoice_number',
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='amount_to_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='e_invoice_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='ewaybill_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='invoice_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='invoice_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.invoicestatus'),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_cgst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_igst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_item_total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_price_after_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='sum_of_sgst_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custominvoice',
            name='updated_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_product_items', to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_product_items', to='Crm_app.customuser'),
        ),
    ]
