# Generated by Django 4.2.8 on 2024-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0023_rename_item_name_custominvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstratevalues',
            name='gstrates',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
