# Generated by Django 4.2.8 on 2024-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0024_alter_gstratevalues_gstrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changerequestcompanydetails',
            name='pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
