# Generated by Django 4.2.8 on 2024-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0025_changerequestcompanydetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequestcompanydetails',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
