# Generated by Django 4.2.8 on 2024-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0026_alter_changerequestcompanydetails_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
