# Generated by Django 4.2.8 on 2024-02-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0027_alter_customuser_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='e_waybill_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
