# Generated by Django 4.2.8 on 2024-02-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0028_einvoice_e_waybill_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einvoice',
            name='e_waybill_payload',
        ),
    ]
