# Generated by Django 4.2.8 on 2024-02-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0030_einvoice_invoice_number_custominvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('transmode', models.CharField(blank=True, max_length=50, null=True)),
                ('transid', models.CharField(blank=True, max_length=50, null=True)),
                ('transname', models.CharField(blank=True, max_length=50, null=True)),
                ('transDocDt', models.CharField(blank=True, max_length=50, null=True)),
                ('transDocNo', models.CharField(blank=True, max_length=50, null=True)),
                ('vehNo', models.CharField(blank=True, max_length=50, null=True)),
                ('vehType', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.additem')),
                ('invoice_number_custominvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.custominvoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customuser')),
            ],
        ),
    ]
