# Generated by Django 4.2.8 on 2024-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0031_transportationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationdetails',
            name='invoice_number_custominvoice',
        ),
        migrations.AlterField(
            model_name='transportationdetails',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
