# Generated by Django 4.2.8 on 2024-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0033_changerequestcompanydetails_email_altr'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='ewaybill_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
