# Generated by Django 4.2.8 on 2024-02-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0035_unitpricelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitpricelist',
            old_name='unit_price',
            new_name='units',
        ),
        migrations.AddField(
            model_name='drone',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.unitpricelist'),
        ),
    ]
