# Generated by Django 4.2.8 on 2024-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0036_rename_unit_price_unitpricelist_units_drone_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvoice',
            name='ewaybill_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
