# Generated by Django 4.2.8 on 2024-03-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0037_custominvoice_ewaybill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_items', to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='customer_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customercategory'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='invoice_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.invoicestatus'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='invoice_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.invoicetype'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_items', to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_items', to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='customer_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customercategory'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='invoice_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.invoicestatus'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='invoice_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.invoicetype'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_product_items', to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.role'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='custom_price',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customizableprice'),
        ),
        migrations.AlterField(
            model_name='dronesales',
            name='custom_price',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customizableprice'),
        ),
        migrations.AlterField(
            model_name='dronesales',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.role'),
        ),
        migrations.AlterField(
            model_name='dronesales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.drone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.role'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.customuser'),
        ),
    ]
