# Generated by Django 4.2.8 on 2024-03-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0038_alter_additem_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Crm_app.drone'),
        ),
    ]
