# Generated by Django 4.2.8 on 2024-03-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0039_additem_drone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='drone',
        ),
    ]
