# Generated by Django 4.2.8 on 2024-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0040_remove_additem_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequestcompanydetails',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
