# Generated by Django 4.2.8 on 2024-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0042_alter_changerequestcompanydetails_user_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='transportation_details',
            field=models.BooleanField(default=False),
        ),
    ]
