# Generated by Django 4.2.8 on 2024-03-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0043_additem_transportation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='transportation_details',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
