# Generated by Django 4.2.8 on 2024-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0047_alter_changerequestcompanydetails_user_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gstin_reg_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
