# Generated by Django 4.2.8 on 2024-03-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0048_customuser_gstin_reg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequestcompanydetails',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
